select
    *
from IMAGES I
where
        I.CREATED_DATE >= DATE_SUB(CURDATE() - 7, INTERVAL WEEKDAY(CURDATE()) DAY) AND
        I.CREATED_DATE <= DATE_SUB(CURDATE() - 1, INTERVAL WEEKDAY(CURDATE()) DAY);